# Generated by Django 2.1.1 on 2019-10-02 05:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190928_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
            ],
            options={
                'db_table': 'ArticleStatistic',
            },
        ),
        migrations.AlterModelTable(
            name='post',
            table='article',
        ),
        migrations.AddField(
            model_name='articlestatistic',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
