# Generated by Django 2.1.1 on 2019-10-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191002_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestatistic',
            name='article',
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
        migrations.DeleteModel(
            name='ArticleStatistic',
        ),
    ]
